project:
  type: website
  output-dir: docs

website:
  title: "pkgdocs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - usethis.qmd

format:
  html:
    theme:
      light: pulse
      dark: vapor
    css: styles.css
    toc: true



