project:
  type: website
  output-dir: docs

website:
  title: "pkgdocs"
  navbar:
    left:
      - usethis.qmd
    right:
      - icon: house-door-fill
        href: https://wzbillings.com
      - icon: github
        href: https://github.com/wzbillings/pkgdocs

format:
  html:
    theme:
      light: pulse
      dark: vapor
    css: styles.css
    toc: true



